language: node_js
node_js:
- 6
- 7
cache: yarn
script:
- yarn run eslint
- yarn run flow
- yarn run cover
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: T6QQLewrhyLr5sgQFrzR1T0VUNbeP3QXfFoYKS1xZKwJdJpppdxE4D9WlOkRr5TwJS6MK8RquB+is0tKLRlQGLzX5vbK/ygX6oJ7g9hTFBRHpSMGfd1cajigslGVs01oi9MCOci2YEBmVlkEmuVMrOUEKAyc61Ky2GCDYFBS0lt9ZGmnh5nfo/Rl0Js+AuDjWztiVb/oi0Nmx55Y6OJKiL+5jbsMAZFyYdf0qH7Tlm+Lyl6S1eqw0QQ6lvJAgvdtG3loKLk0+kYpV+8Etp9dcooqY5WvNgSwAO2Ur34AD/AlMzI68IBq8+ki75zG0sIPrYQbzI/MaawIVJskoSBX6uydZxomzpvVM7eOFREOvpBWHQEWBFoBgJk3gi09wk4FrtClBxgJ6yWlpl4IKsuAzsVOqGH2YkiOWAVpjPxPDQgI5iIBr4OxMMilp5YQMOmPTfnLou68HTlMbE7G+RnKFZiNXVsUAc8fZFhurYQ+zxY5cgC3qtOnUZk9PlwAYzATsTE1A+UvCEX1eK8E9Q8fERUWsmda0GNCkVlVw8ZCbOqfkrOCk3nHUNx4JbISwfhKAdVDUyWlkwyrgKW43LubFincFfj1hhrPRQlGIq0jtRqiz5kg1xzMUuBeb1v0w5xM8T8/4F2iqaFcl1qrpmu9GtXHtSPJpTbIXxM5ydH8g2Q=
  on:
    tags: true
    repo: intel-hpdd/flat-map-changes
